//
//  HomeListViewController.swift
//  HomegateTestAssignmentUIKit
//
//  Created by Vladimir Lukic on 23.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeListDisplayLogic: AnyObject
{
    func displaySomething(viewModel: HomeList.Something.ViewModel)
}

class HomeListViewController: BaseViewController, HomeListDisplayLogic
{
    var interactor: HomeListBusinessLogic?
    var router: (NSObjectProtocol & HomeListRoutingLogic & HomeListDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = HomeListInteractor()
        let presenter = HomeListPresenter()
        let router = HomeListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        // Test network call
        PropertiesNetworkManager.getProperties { result, status, error in
            print(result ?? "")
            print(status ?? "")
            print(error ?? "")
        }
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = HomeList.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: HomeList.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}
