//
//  HomeListInteractor.swift
//  HomegateTestAssignmentUIKit
//
//  Created by Vladimir Lukic on 23.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeListBusinessLogic
{
  func doSomething(request: HomeList.Something.Request)
}

protocol HomeListDataStore
{
  //var name: String { get set }
}

class HomeListInteractor: HomeListBusinessLogic, HomeListDataStore
{
  var presenter: HomeListPresentationLogic?
  var worker: HomeListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: HomeList.Something.Request)
  {
    worker = HomeListWorker()
    worker?.doSomeWork()
    
    let response = HomeList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
