# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HomegateTestAssignmentUIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomegateTestAssignmentUIKit
  
  # Image handling
  pod 'SDWebImage'

  target 'HomegateTestAssignmentUIKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HomegateTestAssignmentUIKitUITests' do
    # Pods for testing
  end

end
