//
//  TabMenuContainerInteractor.swift
//  HomegateTestAssignmentUIKit
//
//  Created by Vladimir Lukic on 23.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TabMenuContainerBusinessLogic
{
    func handleViewControllerInitialisation(request: TabMenuContainer.InitControllers.Request)
    func handleTabBarButtons(request: TabMenuContainer.TabButton.Request)
}

protocol TabMenuContainerDataStore
{
    //var name: String { get set }
}

class TabMenuContainerInteractor: TabMenuContainerBusinessLogic, TabMenuContainerDataStore
{
    var presenter: TabMenuContainerPresentationLogic?
    var worker: TabMenuContainerWorker?
    //var name: String = ""
    
    // MARK: - Implement interactor functions
    // MARK:
    
    // MARK: View controller initialisation
    
    func handleViewControllerInitialisation(request: TabMenuContainer.InitControllers.Request) {
        presenter?.presentViewControllerInitialisation(response: TabMenuContainer.InitControllers.Response())
    }
    
    // MARK: Tab bar buttons handling
    
    func handleTabBarButtons(request: TabMenuContainer.TabButton.Request) {
        presenter?.presentTabBarButtons(response: TabMenuContainer.TabButton.Response(sender: request.sender))
    }
}
