//
//  TabMenuContainerInteractor.swift
//  HomegateTestAssignmentUIKit
//
//  Created by Vladimir Lukic on 23.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TabMenuContainerBusinessLogic
{
  func doSomething(request: TabMenuContainer.Something.Request)
}

protocol TabMenuContainerDataStore
{
  //var name: String { get set }
}

class TabMenuContainerInteractor: TabMenuContainerBusinessLogic, TabMenuContainerDataStore
{
  var presenter: TabMenuContainerPresentationLogic?
  var worker: TabMenuContainerWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: TabMenuContainer.Something.Request)
  {
    worker = TabMenuContainerWorker()
    worker?.doSomeWork()
    
    let response = TabMenuContainer.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
