//
//  HomeDetailsInteractor.swift
//  HomegateTestAssignmentUIKit
//
//  Created by Vladimir Lukic on 23.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeDetailsBusinessLogic
{
  func doSomething(request: HomeDetails.Something.Request)
}

protocol HomeDetailsDataStore
{
  //var name: String { get set }
}

class HomeDetailsInteractor: HomeDetailsBusinessLogic, HomeDetailsDataStore
{
  var presenter: HomeDetailsPresentationLogic?
  var worker: HomeDetailsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: HomeDetails.Something.Request)
  {
    worker = HomeDetailsWorker()
    worker?.doSomeWork()
    
    let response = HomeDetails.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
