//
//  FavoritesListInteractor.swift
//  HomegateTestAssignmentUIKit
//
//  Created by Vladimir Lukic on 23.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritesListBusinessLogic
{
  func doSomething(request: FavoritesList.Something.Request)
}

protocol FavoritesListDataStore
{
  //var name: String { get set }
}

class FavoritesListInteractor: FavoritesListBusinessLogic, FavoritesListDataStore
{
  var presenter: FavoritesListPresentationLogic?
  var worker: FavoritesListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: FavoritesList.Something.Request)
  {
    worker = FavoritesListWorker()
    worker?.doSomeWork()
    
    let response = FavoritesList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
