//
//  FavoritesListInteractor.swift
//  HomegateTestAssignmentUIKit
//
//  Created by Vladimir Lukic on 23.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritesListBusinessLogic
{
    // Call API
    func handlePropertyList(request: FavoritesList.PropertyList.Request)
}

protocol FavoritesListDataStore
{
    //var name: String { get set }
}

class FavoritesListInteractor: FavoritesListBusinessLogic, FavoritesListDataStore
{
    var presenter: FavoritesListPresentationLogic?
    var worker: FavoritesListWorker?
    //var name: String = ""
    
    // MARK: Call Core Data
    
    func handlePropertyList(request: FavoritesList.PropertyList.Request) {
        
        // Get all favoriteproperties
        do {
            let favorites: [PropertyModel] = try CoreDataManager.fetchAllFavorites()
            
            // Call presenter with response
            presenter?.presentPropertyList(response: FavoritesList.PropertyList.Response(result: favorites, error: nil))
        } catch let error as NSError {
            
            // Call presenter with error
            presenter?.presentPropertyList(response: FavoritesList.PropertyList.Response(result: nil, error: error))
        }
    }
}
