//
//  FavoritesListPresenter.swift
//  HomegateTestAssignmentUIKit
//
//  Created by Vladimir Lukic on 23.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritesListPresentationLogic
{
  func presentSomething(response: FavoritesList.Something.Response)
}

class FavoritesListPresenter: FavoritesListPresentationLogic
{
  weak var viewController: FavoritesListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: FavoritesList.Something.Response)
  {
    let viewModel = FavoritesList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
