//
//  FavoritesListModels.swift
//  HomegateTestAssignmentUIKit
//
//  Created by Vladimir Lukic on 23.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FavoritesList
{
    // MARK: Use cases
    
    enum PropertyList
    {
        struct Request
        {
        }
        struct Response
        {
            var result: [PropertyModel]?
            var error: NSError?
        }
        struct ViewModel
        {
            var proppertyList: [PropertyModel]
        }
        struct Error
        {
            var error: NSError
        }
    }
}
