//
//  HomeModels.swift
//  HomegateTestAssignmentUIKit
//
//  Created by Vladimir Lukic on 25.10.21..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
    // MARK: Use cases
    
    enum PropertyList
    {
        struct Request
        {
        }
        struct Response
        {
            var result: String?
            var status: Int?
            var networkError: NetworkError?
        }
        struct ViewModel
        {
            var proppertyList: [PropertyModel]
        }
        struct Error
        {
            var error: NetworkError
        }
    }
    
    enum FavoriteList
    {
        struct Request
        {
        }
        struct Response
        {
            var result: [Int]?
            var error: NSError?
        }
        struct ViewModel
        {
            var favoriteIdList: [Int]
        }
        struct Error
        {
            var error: NSError
        }
    }
    
    enum UpdateFavorite
    {
        struct Request
        {
            var model: PropertyModel
        }
        struct Response
        {
            var error: NSError?
        }
        struct ViewModel
        {
        }
        struct Error
        {
            var error: NSError
        }
    }
}
